# Numpy cheet sheet

https://assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 5])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)

In [5]:
a

array([1, 2, 5])

In [6]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
len(b)

2

In [10]:
len(a)

3

In [11]:
a.ndim

1

In [12]:
b.ndim

2

In [13]:
a.size

3

In [14]:
a.dtype

dtype('int64')

In [15]:
b.size

6

In [16]:
c = np.array([4, -1, 3])

In [17]:
a

array([1, 2, 5])

In [18]:
c

array([ 4, -1,  3])

In [20]:
a+c

array([5, 1, 8])

In [21]:
a*c

array([ 4, -2, 15])

In [23]:
a == c

array([False, False, False])

In [24]:
a < 2

array([ True, False, False])

In [25]:
a.min()

1

In [26]:
a.mean()

2.6666666666666665

In [27]:
np.std(a)

1.699673171197595

In [28]:
a.sort()

In [29]:
a

array([1, 2, 5])

In [30]:
a[0]

1

In [31]:
a[0:2]

array([1, 2])

In [32]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [33]:
b[0:2,1] 

array([2., 5.])

In [34]:
b[:1]

array([[1.5, 2. , 3. ]])

In [35]:
a

array([1, 2, 5])

In [36]:
a[ : :-1]

array([5, 2, 1])

In [37]:
a[a<2] 

array([1])

In [38]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [40]:
i = np.transpose(b)

In [41]:
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [42]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [43]:
b.ravel() 

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [44]:
b.reshape(3,-2)

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [45]:
np.insert(a, 1, 5)

array([1, 5, 2, 5])

In [47]:
a

array([1, 2, 5])

In [46]:
np.delete(a,[1])

array([1, 5])

In [48]:
h = np.array([7, 9])

In [49]:
np.append(a,h) 

array([1, 2, 5, 7, 9])

In [51]:
 np.concatenate((a, h),axis=0)

array([1, 2, 5, 7, 9])

In [52]:
a

array([1, 2, 5])

In [53]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [54]:
np.vstack((a,b))

array([[1. , 2. , 5. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])